language: java
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk11

env:
  matrix:
    - GRADLE_VERSION=default
    - GRADLE_VERSION=5.2.1
  global:
    - SONAR_HOST_URL="https://sonarcloud.io"

    # SONAR_LOGIN value
    # please note this value is available for pull requests from the same repository only
    # see https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
    - secure: "QBQB+KOAl5yD9UXyKGnrQkZ5MmFyMGs5kCk1YQBAb/mi1tUMw5WaDkn65gqHBi2PEvrtdv9CbqXa6HW357bfQEv3k3vPrTG9jTGTopSzlboJPHd6DlpzepNHIBvG1uYmwpPGU0WTP9EhSpSCh6Vk8VmYWz4t13u6aQsW1Ae4rUkVJRNqwbao15u2e/tNyE7LEYfg7lL+mgCOsTfY8Z8R5rpKNMZfNoHvBmLh8luHeOm7isuWc5CVC+7KdV28ubG+JRUTdG3Wc6R1P6wVMkwpGMX6lYvJAQZCuRa7UjOLQ6vrFkSr+X55D08a2V1TqgPyvQVAqorSVnSPB1M7WGIqdJgehaMlQ+pOIsk/cx0BScX2EainwBcsj7I2nOvj1aDLC9hqTkBhPh/JOU7SxLFF+Xms6kd8CtdO9Dog0idhXx81fno/d0BYbXNs4rq798QEM0MLhoqx7Nu3sPTOxxNnvcOY2bnzTuvIt5+Z1kp4jOVJBaUVJZUPtveJnx2tpkcMObX433TjZPQiDyVbgGqfQpO8WZhm/gI9yE8CPooHBSrGmD8D5j923IZIHjKxe+4IpHskISWCkIy6CTGnAP442g7L576wO8kvp43DAlVUmTA/fvTK9wCZFpRi5Q3Ri1up89K5bT6tHKpMDvLPc0NrNWAI/6r1lbRhQwIETs+bU2I="

    # GITHUB_TOKEN value to push changes to GitHub; Currently it is ued to update gh-pages branch of spotbugs/eclipse-latest etc.
    - secure: "IPHrqDG+j+hV9arSOwcu0YrUY+2SPODwLOFUI8SYGyvgO/y861G96UcqFy+v0DjhLQ7dnA1MFznP6rhqbdDYnSLwnO/0gbgMs+YAQFAG/u94aaIM5S8MrYJtqkZATrjLUn4sL2dXT3Vp6Ii3WWgdZ4EMFrDGCzB+f36KwR+AcoSqi296lwUEpSb4k52OWs0cmEj82rz0ZzMNMGQKKlBsHdJJ++XQuWfcECuc4Ck0bvNIg8wA4HYq+qbZoVAwZZKblLQkoqj2aZJgsXpECCSAdTOYtauA/iZE2g9uHYvd7aUIfXEfi9jZQEk+lpNLsMDESobAW5f8mOtHhGgExw+ONrfFzXqZ9eabIC04wj+mBQZvvl+QjsP1wUwGQKIlCN8lMBai9he7yBp1P2CB9TB3N1OBEhZv26Z+HO5eLX68EnsiEm+L6te0YwRettNdwXzyR23sGE4tFX/VNmuaXhOZL4Glh33yIIK8CXH7y9GSgHq9mxKDy3qwqQvGuiQ/Pnhe2gmEYeK5gDPxvdGRNERTS2yJKhYgGOn+cH5xST4lUNX6A6UPCMLAMwHLDDNRGQSOqhOp36o7uS+7omBP79LhA+fKD43AhlkH8j/cUfy3ZeqcZh4FeSbi+2nKjwaDKeClecvQ/SudnbuyqVKSNpgxj+TfoObbqg3Zhp8xHr9NfPA="
    # GRADLE_PUBLISH_KEY value
    - secure: "mMr4tGCgUQl6K7/TeGEDpXYctyQC4UaqjGWwaUAGVcndKvQtgFNsEPKnzPBfZZ7tx/1PFS+qnqmOOsh53GzAmVJlBcYjb65Cd0nqQjQt3BrbgmZ9rX8tsKwpoPnL28U/Gl0XgWMPOHl6BaSudASFVe2qOF+AIcbwjJgNOiRtnDLBJAoJ54mOFdxn9K4D978b2Top6hjtz6SwjZ0CYnCTZ6uKuIDRpPHyZCjXXZxhw5ddpzfpMXq05+KFZV5neDj/3v0SlBZtRCEVvJSUUvkBauiEkQyCCO4cPTTLBwK2kAFcxF8LAhfKjRjQgexsokEGMz/nPmkhP61xR5+k1SySDXpIrMUHwHeASooRV1uyM0PZSGd2y/ATNkA3qoMGPYNpVGjshTFcNpyZybtd0qGVHKJkO35UB+Gjyd08G2/a8MkBSZg5MNd4iWNeBI78OP6Ay6YgenNzF1Ux7IKHMlguuRwmS4nck0JG6HIYlsFED3Z9owquY+niBmJXoW2fp1iGteGMyRgMBXht9mCSq6nrCV+waFVPnC+m9wQY7XuEfsr9IloPggK2jm+RP7AdmgAGGT9FOt8hDYjZOhRJTCxB8cQZSH7JVaLk2/SZWl3Iy4jjtDybsVTRH3P37tg33mclAf37EV92b3gdMT9cj6+KLUzI96kDRAA7WKKXPnbBqJw="
    # GRADLE_PUBLISH_SECRET value
    - secure: "jvxgv7af11mQj0gquhMkFB3ITD3PPvkO67ORHosqUgUF/hhtDx8UcED2MLOsSI1FV0C8li85h0hccQrxQeh2V+b+eq1tgRDd28xwyarNNkHTxIS7i1Yox4zDSwvDrvE4CC01n0fgpXvSwNFrmtdrVIUXhM2/CilwbRCHXyI6XARD2jbR89oViapimMcfVe62g/0olWUW+qtQ4nJAE0XWGlSBoKNNhw2TerLncgNDoDGot2D6vBvr8Knu5atO5DDOP1VlLZcM11CHEANFivIN412D2pPfvwKgrsNMnFsInw+ZgNhVX1jKsB2dBL94n/64s2k3Ni8yl1k+1DMlS03EfaKXCoo2DiAScTc6D+dgMHvN3vvauMQDa/6bW6QxS00OmHcEyzwOOtUEpsu7qLm4qW47hzjDWP/NILQwsbtFWA1FjydnCcxsj9lV9nkDFK6rWml/V/z5NI0zkTqTbucLyKITp7pxZ0cLwjxUv7bQeT+yTZKFrBrvGa+Gk9BFolckIjQQGOlO40gATfsmdsq6Fx3LB8aJ32UstS1RLCmVn4BpeK/Mqg/23ivqko2nbxY7x1dDCxAMlPrjAe7swzKVdQlXMQ6Sf+fU8Ql1lBf6EZ2OzDZEiSwgcPzIFV7gqcrE/3Uq/vMFG46zTXymIDPtzMugp5HrhxjbqP8IGYZZ5lQ="

addons:
  apt:
    update: true
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
  sonarcloud:
    organization: "spotbugs"

install:
  - if [[ $GRADLE_VERSION != "default" ]]; then ./gradlew wrapper --gradle-version $GRADLE_VERSION; fi

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew classes testClasses -S
  - if [[ $TRAVIS_JDK_VERSION == "oraclejdk11" ]]; then export JAVA_HOME=$HOME/oraclejdk11; fi
  - ./gradlew -v --no-daemon
  - ./gradlew check -S --no-daemon

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: analyze
      script: ./gradlew sonarqube -S
    - stage: deploy
      name: Deploy to Gradle Plugin Portal
      script: skip
      if: tag IS present
      deploy:
        - provider: script
          script: ./gradlew publishPlugins -Pgradle.publish.key="$GRADLE_PUBLISH_KEY" -Pgradle.publish.secret="$GRADLE_PUBLISH_SECRET"
          on:
            tags: true
    - name: Deploy to Sonatype Snapshot Repository
      script: skip
      if: (branch = master) AND (type = push)
      deploy:
        - provider: script
          script: ./gradlew uploadArchives -PossrhUsername="$SONATYPE_USERNAME" -PossrhPassword="$SONATYPE_PASSWORD"
          on:
            branch: master
